# Site settings
title: ptighe.info
email: your-email@domain.com
description: Homepage and development site for Patrick Tighe.  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.ptighe.info.s3-website-us-east-1.amazonaws.com" # the base hostname & protocol for your site
twitter_username: ptighe
github_username:  ptighe

# Build settings
markdown: kramdown
